import { decennaleGarantieRows } from "@/lib/decennale-garanties-affichage"
import { DO_GARANTIES_LEGALES } from "@/lib/nomenclature-activites"
import { DEFAULT_PUBLIC_CONTACT_EMAIL } from "@/lib/public-contact-email"
import { SITE_URL } from "@/lib/site-url"

/**
 * Rubriques que les conditions particulières du marché indiquent toujours
 * (activités, zone, franchise, plafonds, durée, paiement).
 * Texte propre à Optimum : les conditions générales des concurrents ne sont pas reprises.
 */

export const DECENNALE_CP_CADRE = [
  "En cas de divergence, les conditions particulières prévalent sur les conditions générales.",
  "Seules les activités inscrites au contrat sont garanties. Une activité exercée mais absente de cette liste n'est pas couverte.",
  "Zone d'intervention : France métropolitaine, pour les travaux qui correspondent aux activités déclarées.",
  "La franchise s'applique par sinistre. Pour la garantie décennale obligatoire, elle reste à la charge de l'assuré et n'est pas opposable au maître d'ouvrage.",
  "Le plafond de la responsabilité civile décennale s'applique par sinistre. Lorsqu'un chiffre d'affaires annuel est déclaré, ce plafond est égal à deux fois ce chiffre d'affaires.",
  "Les techniques non courantes et les procédés qui s'écartent des activités déclarées doivent être signalés avant le début des travaux. À défaut, ils restent hors garantie.",
  "Les travaux confiés en sous-traitance ne sont couverts que s'ils entrent dans les activités déclarées.",
  "Durée : contrat annuel, reconduit sauf résiliation dans les formes prévues, au plus tard deux mois avant l'échéance, après une première année.",
  "Paiement : prime annuelle TTC, fractionnée par trimestre. Le premier règlement suit le parcours de souscription, les échéances suivantes le prélèvement SEPA.",
] as const

/**
 * Régime légal de la responsabilité civile décennale.
 * Texte d'Optimum : il expose le Code des assurances et le Code civil.
 * L'annexe I de l'article A.243-1 vise l'assurance de responsabilité ; l'annexe II vise l'assurance de dommages.
 */
export const DECENNALE_REGIME_EXPERT = [
  "Personnes tenues de s'assurer. L'article L.241-1 du Code des assurances impose une assurance à toute personne physique ou morale dont la responsabilité décennale peut être engagée sur la présomption des articles 1792 et suivants du Code civil. À l'ouverture de chaque chantier, elle justifie qu'elle a souscrit un contrat couvrant cette responsabilité. Le candidat à un marché public doit être en mesure d'en justifier. Le contrat est réputé comporter, nonobstant toute clause contraire, le maintien de la garantie pendant toute la durée de cette responsabilité.",
  "Fabricants, importateurs et contrôleurs techniques. L'article L.241-2 étend l'obligation aux fabricants et importateurs d'un ouvrage, d'une partie d'ouvrage ou d'un élément d'équipement conçu et produit pour satisfaire, en état de service, à des exigences précises et déterminées à l'avance, et au contrôleur technique dont la responsabilité peut être recherchée sur le fondement de l'article 1792. L'article 1792-4 du Code civil rend le fabricant, et celui qui est assimilé à un fabricant, solidairement responsable avec le locateur d'ouvrage qui a mis en œuvre l'élément sans le modifier et conformément aux règles du fabricant.",
  "Sanction et dispenses. L'article L.243-3 punit le défaut d'assurance des articles L.241-1 à L.242-1 d'un emprisonnement de six mois et d'une amende de 75 000 EUR, ou de l'une de ces deux peines. Cette peine ne s'applique pas à la personne physique qui construit un logement pour l'occuper elle-même ou le faire occuper par son conjoint, ses ascendants, ses descendants ou ceux de son conjoint. L'article L.243-1 écarte l'obligation lorsque l'État construit pour son compte et permet une dérogation aux collectivités et établissements publics qui peuvent réparer vite et complètement.",
  "Ouvrages hors obligation. L'article L.243-1-1 écarte l'obligation pour les ouvrages maritimes, lacustres et fluviaux, les infrastructures routières, portuaires, aéroportuaires, héliportuaires et ferroviaires, les ouvrages de traitement de résidus et de déchets, ainsi que leurs éléments d'équipement. Sauf accessoire d'un ouvrage soumis à l'obligation, les voiries, parcs de stationnement, réseaux, ouvrages d'énergie, de télécommunications et ouvrages sportifs non couverts sont aussi hors obligation. Un ouvrage non visé par cet article reste soumis à l'obligation, même s'il est l'accessoire d'un ouvrage exclu.",
  "Objet de la garantie obligatoire. L'assureur paie les travaux de réparation des dommages, même résultant d'un vice du sol, de la nature de ceux dont l'assuré est responsable au titre des articles 1792 et 1792-2 du Code civil : atteinte à la solidité de l'ouvrage, ou impropriété à sa destination, y compris les éléments d'équipement indissociables des ouvrages de viabilité, de fondation, d'ossature, de clos ou de couvert. La réparation comprend, lorsqu'ils sont nécessaires, la démolition, le déblaiement, la dépose et le démontage. Cette garantie n'est pas une assurance dommages-ouvrage : elle suppose que la responsabilité de l'assuré soit engagée, et les délais de soixante et quatre-vingt-dix jours de l'article L.242-1 ne s'appliquent pas à l'assureur de responsabilité.",
  "Ce que la garantie obligatoire ne paie pas. Les dommages immatériels qui ne sont pas le coût de réparation de l'ouvrage relèvent, s'ils sont souscrits, de la responsabilité civile professionnelle, et non de la garantie obligatoire. La franchise de cette garantie professionnelle reste opposable. La garantie de parfait achèvement de l'article 1792-6 demeure l'obligation de l'entrepreneur pendant un an après la réception. La garantie de bon fonctionnement des éléments d'équipement dissociables, article 1792-3, dure deux ans à compter de la réception et n'est acquise que dans les limites du tableau des garanties. Toute clause qui écarterait la responsabilité des articles 1792 et suivants est réputée non écrite par l'article 1792-5.",
  "Réception et durée. La réception, article 1792-6, est l'acte par lequel le maître de l'ouvrage accepte l'ouvrage avec ou sans réserves. Les vices apparents acceptés sans réserve ne sont pas garantis au titre décennal. La responsabilité et les garanties des articles 1792 et suivants s'éteignent dix ans après la réception, par la forclusion de l'article 1792-4-1. Ce délai n'est pas une prescription.",
  "Maintien de la garantie. L'annexe I à l'article A.243-1 couvre, pour la durée de la responsabilité des articles 1792 et suivants, les travaux dont le chantier a été ouvert pendant la période de validité des conditions particulières. Cette garantie est maintenue dans tous les cas pour la même durée, sans paiement d'une prime subséquente, même si le contrat annuel a pris fin. L'article L.241-1 répute cette clause acquise nonobstant toute stipulation contraire. Un chantier ouvert après la fin ou la suspension du contrat n'entre pas dans ce maintien.",
  "Contrat annuel. La police est annuelle. Elle se reconduit sauf résiliation dans les formes de l'article L.113-12 du Code des assurances, notifiée au plus tard deux mois avant l'échéance, après une première année. Les articles L.113-16 et le deuxième alinéa de l'article L.121-10 ne s'appliquent pas aux assurances obligatoires de la construction : un sinistre ne permet pas de résilier la garantie obligatoire déjà acquise, et la cession du bien assuré ne la fait pas cesser dans les conditions du droit commun. Le défaut de paiement d'une prime échue peut suspendre puis résilier le contrat selon l'article L.113-3, sans effacer le maintien des chantiers déjà ouverts pendant que le contrat produisait effet.",
  "Montant. Le plafond indiqué aux conditions particulières s'applique par sinistre. Lorsqu'un chiffre d'affaires annuel est déclaré, ce plafond contractuel est égal à deux fois ce chiffre d'affaires. Pour la seule garantie obligatoire, ce plafond ne peut pas être moins favorable que l'annexe I : en habitation, l'indemnité correspond au coût de réparation ; hors habitation, à ce coût dans la limite du coût total de construction déclaré par le maître de l'ouvrage. Le plancher de l'article R.243-3 est ce coût déclaré, plafonné à 150 millions d'euros lorsque le coût déclaré excède ce montant. Le chiffre d'affaires déclaré est l'assiette de la prime. Toute augmentation est déclarée avant qu'elle ne soit exécutée.",
  "Franchise. L'assuré conserve à sa charge la franchise fixée aux conditions particulières et ne peut pas s'assurer pour cette portion du risque. Pour la garantie obligatoire de réparation de l'ouvrage, cette franchise n'est pas opposable au maître de l'ouvrage ni aux autres bénéficiaires des indemnités. Elle leur reste opposable pour les garanties facultatives et pour les dommages immatériels.",
  "Activités, techniques et sous-traitance. Seules les activités inscrites au contrat sont garanties. Une activité exercée mais non déclarée n'est pas couverte. Les techniques non courantes sont déclarées avant leur mise en œuvre ; sans acceptation écrite, elles restent hors garantie. Le sous-traitant reste personnellement soumis à l'article L.241-1 pour le lot qu'il exécute. Les travaux que l'assuré confie en sous-traitance ne sont couverts par son contrat que s'ils entrent dans ses activités déclarées. La reprise d'un chantier déjà ouvert n'est acquise que si elle est expressément acceptée.",
  "Exclusions. Elles sont rédigées en caractères apparents, conformément à l'article L.112-4. Conformément à l'annexe I de l'article A.243-1, la garantie obligatoire ne s'applique pas aux dommages résultant exclusivement du fait intentionnel ou du dol du souscripteur ou de l'assuré, des effets de l'usure normale, du défaut d'entretien ou de l'usage anormal, et de la cause étrangère. Ces exclusions ne peuvent pas ramener la garantie obligatoire au-dessous de cette annexe.",
  "Déchéance pour règles de l'art. L'annexe I prévoit la déchéance de l'assuré en cas d'inobservation inexcusable des règles de l'art, telles qu'elles résultent des réglementations en vigueur, des normes françaises homologuées ou des normes d'un autre État membre de l'Union européenne ou partie à l'accord sur l'Espace économique européen offrant une sécurité équivalente. Cette inobservation s'entend d'un choix constructif manifestement absurde, fait en connaissance de cause. Pour l'appliquer, l'assuré s'entend du souscripteur personne physique, du chef d'entreprise ou du représentant statutaire si l'entreprise est inscrite au répertoire des métiers, ou des représentants légaux lorsque l'assuré est une personne morale. Cette déchéance n'est pas opposable aux bénéficiaires des indemnités dues au titre de la garantie obligatoire.",
  "Déclarations et aggravation. Les réponses du questionnaire sont déterminantes du consentement de l'assureur, articles L.113-2, L.113-8 et L.113-9. La réticence ou la fausse déclaration intentionnelle entraîne la nullité. Lorsque la mauvaise foi n'est pas établie, l'indemnité est réduite en proportion des primes. L'article L.113-4 s'applique à une aggravation en cours de contrat, notamment un changement d'activité, de technique ou de chiffre d'affaires : l'assureur peut proposer une prime nouvelle ou dénoncer le contrat dans les délais de cet article, qu'il rappelle à l'assuré. Il ne peut plus invoquer l'aggravation s'il a maintenu le contrat après en avoir été informé. Cette faculté ne retire pas le maintien déjà acquis pour les chantiers ouverts.",
  "Déchéances nulles. L'article L.113-11 frappe de nullité la déchéance pour déclaration tardive due à un cas fortuit ou à une force majeure, la clause générale de déchéance pour violation des lois sauf crime ou délit intentionnel, et la déchéance fondée sur un simple retard à déclarer le sinistre aux autorités ou à produire des pièces. Ce retard laisse à l'assureur une indemnité proportionnée au préjudice que le retard lui a causé. Aucune déchéance ne ramène la garantie obligatoire au-dessous de l'annexe I.",
  "Sinistre et action directe. L'assuré déclare le sinistre par écrit, contre récépissé ou par lettre recommandée avec avis de réception, dès qu'il en a connaissance, à " +
    DEFAULT_PUBLIC_CONTACT_EMAIL +
    ". La victime des dommages dispose de l'action directe de l'article L.124-3 contre l'assureur, dans la limite de la garantie. L'assureur peut faire constater les dommages par un expert. Après paiement, il est subrogé dans les droits de la personne indemnisée, article L.121-12, dans la limite de l'indemnité versée. L'indemnité obligatoire est destinée au paiement des travaux de réparation de l'ouvrage et ne peut pas excéder ce coût.",
  "Attestation. Elle justifie la garantie pour la période et les activités qu'elle énonce. Elle ne peut pas engager l'assureur au-delà du contrat et des clauses types. Elle est produite à l'ouverture du chantier et peut être jointe aux devis et aux factures. Pour un chantier, la garantie est celle du contrat en vigueur à l'ouverture, maintenue dix ans à compter de la réception.",
  "Prescription. L'action dérivant du contrat d'assurance, entre l'assuré et l'assureur, se prescrit par deux ans selon l'article L.114-1. Elle est interrompue dans les cas de l'article L.114-2 : reconnaissance du droit par le débiteur (article 2240 du Code civil), demande en justice (article 2241), acte d'exécution forcée (article 2244), désignation d'experts après un sinistre, et lettre recommandée avec avis de réception de l'assuré à l'assureur pour l'indemnité ou de l'assureur à l'assuré pour la prime. Ce rappel est fait conformément à l'article R.112-1. Cette prescription biennale ne se confond pas avec la forclusion décennale de l'article 1792-4-1, qui éteint la responsabilité elle-même.",
  "Proposition, renonciation et distribution. La proposition de l'article L.112-2 n'engage ni le candidat ni l'assureur : seule la police constate l'engagement. Le contrat est rédigé en français, en caractères apparents, article L.112-3. Une personne physique qui souscrit à distance ou hors établissement, pour des besoins étrangers à son activité professionnelle, peut renoncer pendant quatorze jours selon l'article L.112-2-1. La souscription faite pour les besoins de l'activité professionnelle n'ouvre pas cette renonciation. Optimum Courtage agit comme courtier, sans exclusivité d'un assureur, par délégation de l'assureur porteur du risque, et exécute le devoir de conseil des articles L.521-2 et suivants. Toute entreprise d'assurance agréée selon l'article L.321-1 peut couvrir ce risque. L'indemnisation incombe à l'assureur.",
  "Réclamation, données et vigilance. Toute réclamation est d'abord adressée par écrit au courtier, à " +
    DEFAULT_PUBLIC_CONTACT_EMAIL +
    ". Elle est accusée réception dans les dix jours et reçoit une réponse dans les deux mois. Le souscripteur peut ensuite saisir gratuitement La Médiation de l'Assurance, TSA 50110, 75441 Paris Cedex 09, www.mediation-assurance.org, si le litige n'est pas déjà devant un tribunal. Le contrôle prudentiel est celui de l'ACPR, 4 place de Budapest, CS 92459, 75436 Paris Cedex 09. Les données sont traitées pour l'étude, la souscription et la gestion du contrat ; les droits s'exercent auprès du courtier. Le courtier applique les obligations de vigilance des articles L.561-2 et suivants du Code monétaire et financier. Le refus de justifier de l'identité ou de l'origine des fonds bloque l'émission des pièces.",
  "Droit applicable. Le contrat est soumis au droit français. Les tribunaux français sont compétents. En cas de divergence, les conditions particulières prévalent sur les conditions générales, et l'annexe I de l'article A.243-1 prévaut sur toute stipulation moins favorable au titre de la seule garantie obligatoire. Courtier : Optimum Courtage, RCS Angers 450 788 278, ORIAS LPS 28931947, siège 14 rue d'Amboise, 49300 Cholet. Assurance de responsabilité civile professionnelle et garantie financière conformes aux articles L.512-6 et L.512-7.",
] as const

/** Validité des propositions DO émises par Optimum (devis dommage ouvrage). */
export const DO_QUOTE_VALIDITY_DAYS = 90

/** Plafond de coût déjà retenu sur les propositions générées (honoraires et existants inclus). */
export const DO_COUT_MAX_PROPOSITION_LABEL = "1 000 000 EUR TTC (honoraires et existants inclus)"

/** Mentions déjà publiées par Optimum (mentions légales, CGV, Code des assurances). */
export const DO_MENTIONS_JURIDIQUES = [
  "Courtier : Optimum Courtage, RCS Angers 450 788 278, ORIAS LPS 28931947 (libre prestation de services), siège 14 rue d'Amboise, 49300 Cholet. Assurance de responsabilité civile professionnelle et garantie financière conformes aux articles L.512-6 et L.512-7 du Code des assurances.",
  "Contrôle : Autorité de contrôle prudentiel et de résolution (ACPR), 4 place de Budapest, CS 92459, 75436 Paris Cedex 09.",
  `Déclaration de sinistre : l'assuré la transmet par écrit à ${DEFAULT_PUBLIC_CONTACT_EMAIL}, avec la description des dommages, leur date d'apparition et les pièces du chantier. Au titre de l'article L.242-1 du Code des assurances, l'assureur notifie sa décision sur le principe de la garantie dans les 60 jours de la réception de la déclaration, puis présente une offre d'indemnité dans les 90 jours lorsque la garantie est acquise.`,
  "Réclamation : elle est d'abord adressée au courtier. Sans réponse satisfaisante, le souscripteur peut saisir gratuitement La Médiation de l'Assurance, TSA 50110, 75441 Paris Cedex 09, www.mediation-assurance.org, sans préjudice d'une action en justice.",
  "Prescription : deux ans à compter de l'événement qui y donne naissance, selon l'article L.114-1 du Code des assurances, sous réserve des causes d'interruption de l'article L.114-2.",
  "Lorsqu'une personne physique souscrit à distance ou hors établissement en dehors de son activité professionnelle, elle peut renoncer au contrat pendant quatorze jours calendaires, dans les conditions de l'article L.112-2-1 du Code des assurances. La demande d'exécution immédiate avant la fin de ce délai laisse due la prime correspondant à la période déjà courue.",
  `Données personnelles : traitement pour l'étude du risque, la souscription et la gestion du contrat. Droits d'accès, de rectification, d'effacement, d'opposition, de limitation et de portabilité auprès de ${DEFAULT_PUBLIC_CONTACT_EMAIL}. Politique : ${SITE_URL}/confidentialite.`,
  "Lutte contre le blanchiment : des justificatifs d'identité et d'origine des fonds peuvent être demandés. Le refus de les transmettre bloque le dossier.",
] as const

/**
 * Développement du régime légal dommages-ouvrage.
 * Texte d'Optimum : il expose le Code des assurances et le Code civil, il ne reprend pas les conditions générales d'un assureur.
 */
export const DO_REGIME_EXPERT = [
  "Personnes tenues de s'assurer. L'article L.242-1 du Code des assurances impose, avant l'ouverture du chantier, une assurance à toute personne physique ou morale qui, agissant en qualité de propriétaire de l'ouvrage, de vendeur ou de mandataire du propriétaire, fait réaliser des travaux de construction. L'assurance est souscrite pour son compte et pour celui des propriétaires successifs. Elle ne couvre que l'opération et les travaux désignés aux présentes et au questionnaire d'étude. Les travaux accessoires à cette opération ne font pas l'objet d'un contrat distinct : ils sont qualifiés avec l'ouvrage principal. L'obligation ne s'applique pas aux personnes morales de droit public, ni à la personne morale qui assure la maîtrise d'ouvrage dans un contrat de partenariat régi par l'ordonnance n° 2004-559 du 17 juin 2004, ni, pour un usage autre que l'habitation, à la personne morale dont l'activité dépasse les seuils du dernier alinéa de l'article L.111-6 du code de la construction et de l'habitation.",
  "Dispenses et dérogations. L'article L.243-1 du Code des assurances écarte l'obligation lorsque l'État construit pour son compte. Une dérogation totale ou partielle peut être accordée par l'autorité administrative aux collectivités territoriales, à leurs groupements et aux établissements publics qui justifient de moyens permettant la réparation rapide et complète des dommages.",
  "Promoteur immobilier. Dans les contrats de promotion immobilière des articles 1831-1 à 1831-5 du Code civil, et dans les autres cas visés par l'article L.242-2 du Code des assurances, les obligations des articles L.241-2 et L.242-1 incombent au promoteur immobilier. L'article L.242-2 écarte, pour les assurances obligatoires de la construction, l'article L.113-16 et le deuxième alinéa de l'article L.121-10 : la garantie obligatoire ne se résilie pas après un sinistre, et la vente de l'immeuble ne permet ni à l'assureur ni à l'acquéreur de mettre fin à cette garantie.",
  "Sanction du défaut d'assurance. L'article L.243-3 du Code des assurances punit le défaut d'assurance obligatoire d'un emprisonnement de six mois et d'une amende de 75 000 EUR, ou de l'une de ces deux peines. Cette sanction ne s'applique pas à la personne physique qui construit un logement pour l'occuper elle-même ou le faire occuper par son conjoint, ses ascendants, ses descendants ou ceux de son conjoint.",
  "Objet de la garantie obligatoire. L'assurance dommages-ouvrage est une assurance de choses. L'assureur paie la totalité des travaux de réparation des dommages de la nature de ceux dont sont responsables les constructeurs au sens de l'article 1792-1 du Code civil, les fabricants et importateurs ou le contrôleur technique sur le fondement de l'article 1792, sans attendre la détermination des responsabilités. Sont visés les dommages, même résultant d'un vice du sol, qui compromettent la solidité de l'ouvrage ou qui, l'affectant dans un de ses éléments constitutifs ou d'équipement, le rendent impropre à sa destination, y compris la solidité des éléments d'équipement indissociables des ouvrages de viabilité, de fondation, d'ossature, de clos ou de couvert au sens de l'article 1792-2. Les travaux de réparation comprennent, lorsqu'ils sont nécessaires, la démolition, le déblaiement, la dépose et le démontage. Un simple défaut de conformité au marché, qui ne compromet ni la solidité ni la destination, n'est pas garanti. L'assureur ne peut exiger que les réparations soient exécutées avant le versement de l'indemnité : la garantie préfinance ces réparations.",
  "Ce que la garantie obligatoire ne comprend pas. La garantie de bon fonctionnement des éléments d'équipement dissociables, prévue pour deux ans par l'article 1792-3 du Code civil, n'est pas dans l'assurance obligatoire. La garantie de parfait achèvement de l'article 1792-6 du Code civil reste d'abord à la charge de l'entrepreneur pendant un an après la réception. Les dommages immatériels non consécutifs à un dommage matériel garanti, la responsabilité civile du maître d'ouvrage, les tous risques chantier et la responsabilité du constructeur non réalisateur ne sont acquis que s'ils sont expressément souscrits. Toute clause qui limiterait la responsabilité des constructeurs au titre des articles 1792 et suivants est réputée non écrite par l'article 1792-5 du Code civil. Toute stipulation qui réduirait la garantie obligatoire au-dessous de l'annexe II à l'article A.243-1 est sans effet.",
  "Parfait achèvement et point de départ. Pendant l'année qui suit la réception, l'article 1792-6 du Code civil met d'abord à la charge de l'entrepreneur la réparation des désordres signalés par le maître de l'ouvrage, par des réserves au procès-verbal ou par une notification écrite. La garantie obligatoire prend effet après l'expiration de ce délai. Elle paie toutefois les réparations avant ce terme dans les deux cas de l'article L.242-1 : avant la réception, lorsque, après mise en demeure restée infructueuse, le contrat de louage d'ouvrage est résilié pour inexécution de l'entrepreneur ; après la réception et avant la fin du parfait achèvement, lorsque, après mise en demeure par lettre recommandée avec avis de réception restée infructueuse, l'entrepreneur n'a pas exécuté ses obligations. La mise en demeure n'est pas exigée lorsqu'elle est impossible ou inutile, notamment si l'entrepreneur a cessé son activité.",
  "Réception. La réception est l'acte par lequel le maître de l'ouvrage déclare accepter l'ouvrage avec ou sans réserves, au sens de l'article 1792-6 du Code civil. Elle est contradictoire. Elle est expresse lorsqu'elle résulte du procès-verbal, et elle peut aussi résulter d'une volonté non équivoque d'accepter l'ouvrage. Les vices apparents qui n'ont pas été consignés en réserves lors de la réception ne sont pas garantis. Le procès-verbal est signé par le maître de l'ouvrage et par l'entreprise ; si l'entreprise ne se présente pas, la convocation en lettre recommandée est jointe.",
  "Durée et forclusion. Toute personne est déchargée des responsabilités et garanties des articles 1792 et suivants du Code civil après dix ans à compter de la réception, par l'article 1792-4-1 du Code civil. Ce délai est une forclusion. La garantie obligatoire dommages-ouvrage suit ce terme. Une fois prise effet, elle n'est pas résiliable.",
  "La garantie suit l'immeuble. Elle bénéficie au maître de l'ouvrage et aux propriétaires successifs. En cas de vente, l'assuré informe l'assureur et l'acquéreur dans les quinze jours de l'acte authentique. L'étude notariale vérifie qu'aucune prime d'ajustement, aggravation ou pénalité n'est restée impayée : à défaut, l'acquéreur peut être privé de tout ou partie de l'indemnité.",
  "Minimum légal incompressible. L'article A.243-1 impose les clauses de son annexe II pour l'assurance de dommages, et celles des annexes I et III pour l'assurance de responsabilité. L'article L.242-1 répute le contrat comporter des garanties au moins équivalentes à cette annexe II, nonobstant toute clause contraire. Toute autre clause est sans effet si elle en altère la portée, sauf lorsqu'elle ne vise qu'une garantie plus large. Pour un ouvrage à usage total ou principal d'habitation, l'indemnité correspond au coût de réparation des dommages. Hors habitation, elle correspond à ce coût dans la limite du coût total de construction déclaré. Le plancher de l'article R.243-3 est ce coût déclaré, et il est lui-même plafonné à 150 millions d'euros lorsque le coût déclaré excède ce montant. Aucune franchise n'est appliquée sur la garantie obligatoire. L'indemnité obligatoire est revalorisée selon l'indice du coût de la construction publié par l'INSEE, par le rapport entre le dernier indice connu à la date de l'offre et le dernier indice connu à la souscription. En habitation, cette garantie n'est pas un plafond qui s'épuise. Hors habitation, le cumul des indemnités reste dans la limite du coût déclaré, revalorisée. Les garanties facultatives souscrites sont épuisables et ne se reconstituent que par avenant.",
  "Coût total de construction. Il résulte du montant définitif des dépenses de l'ensemble des travaux, toutes révisions, honoraires, taxes et travaux supplémentaires compris. Il intègre la valeur de reconstruction des existants totalement incorporés dans l'ouvrage neuf et qui en deviennent techniquement indivisibles. Il ne comprend ni les primes accordées pour une exécution plus rapide, ni une diminution au titre des pénalités de retard. Les existants qui ne sont pas ainsi incorporés restent hors assiette tant que leur garantie n'est pas souscrite. Ce coût est une condition de la garantie et l'assiette de la prime. S'il dépasse de plus de 10 % le coût prévisionnel, la prime est ajustée au même taux et un avenant est établi avant la poursuite de la garantie sur l'assiette nouvelle.",
  "Base hors taxes. Lorsque le maître d'ouvrage est assujetti à la TVA et que la prime a été calculée hors taxes, les indemnités sont réglées hors taxes. Avant un transfert de propriété, il demande un avenant intégrant la TVA et paie le complément. Les sinistres postérieurs à ce paiement sont indemnisés taxes comprises. À défaut de déclaration ou de paiement, l'indemnité peut être réduite dans la proportion entre la prime payée et la prime qui aurait été due toutes taxes comprises.",
  "Déclaration de sinistre réputée constituée. L'assuré déclare le sinistre par écrit, contre récépissé ou par lettre recommandée avec avis de réception, dès qu'il en a connaissance, à " +
    DEFAULT_PUBLIC_CONTACT_EMAIL +
    ". La déclaration est réputée constituée lorsqu'elle indique le numéro de contrat, le nom du propriétaire, l'adresse de l'ouvrage, la date de réception ou, à défaut, celle de la première occupation, la date d'apparition des dommages, leur description et leur localisation et, pendant le parfait achèvement, la copie de la mise en demeure. L'assureur dispose de dix jours pour signaler qu'un de ces éléments manque. Les délais de l'article L.242-1 courent à compter de la réception de la déclaration réputée constituée. L'assuré laisse accéder à l'ouvrage et conserve les éléments endommagés, sauf mesure conservatoire urgente.",
  "Délais de l'assureur et sanction. L'assureur notifie sa décision sur le principe de la garantie dans les soixante jours. S'il ne la conteste pas, il présente dans les quatre-vingt-dix jours une offre d'indemnité, qui peut être provisionnelle, destinée au paiement des réparations. Après acceptation, le règlement intervient dans les quinze jours. Si l'un de ces délais n'est pas tenu, ou si l'offre est manifestement insuffisante, l'assuré peut, après notification à l'assureur, engager les dépenses de réparation. L'indemnité est alors majorée de plein droit d'un intérêt égal au double du taux de l'intérêt légal. En cas de difficultés exceptionnelles dues à la nature ou à l'importance du sinistre, l'assureur peut, en même temps qu'il accepte le principe de la garantie, proposer un délai supplémentaire fondé sur des motifs exclusivement techniques. Ce délai suppose l'acceptation expresse de l'assuré et ne peut excéder cent trente-cinq jours.",
  "Expertise contradictoire. Les dommages sont constatés par un expert désigné par l'assureur. L'assuré peut le récuser dans les huit jours de la notification de sa désignation. Une seconde récusation conduit l'assureur à faire désigner l'expert par le juge des référés. La première récusation allonge de dix jours les délais d'instruction, et la désignation par le juge des référés les allonge de trente jours. L'expertise est contradictoire : l'assuré peut se faire assister ou représenter, et ses observations sont consignées au rapport. Les réalisateurs, les fabricants au sens de l'article 1792-4 du Code civil, le contrôleur technique et leurs assureurs de responsabilité décennale sont consultés avant le rapport préliminaire et avant le rapport d'expertise. Le rapport préliminaire décrit les mesures conservatoires et les éléments utiles au principe de la garantie. Le rapport d'expertise décrit les travaux de réparation intégrale. L'assureur communique chaque rapport au plus tard en même temps que sa décision. Une décision de refus est motivée. L'assureur peut se dispenser d'expertise lorsque le dommage est inférieur à 1 800 EUR ou lorsque la garantie est manifestement injustifiée : il notifie alors son offre ou son refus dans les quinze jours, en rappelant de façon apparente que l'assuré peut encore obtenir un expert. Si le rapport préliminaire n'est pas communiqué dans le délai de soixante jours, la garantie joue pour le sinistre déclaré et l'assuré peut engager les mesures conservatoires dans la limite de l'estimation du rapport ou, à défaut, de sa propre estimation.",
  "Désaccord, avance et affectation de l'indemnité. Lorsqu'une expertise a été requise et que l'assuré n'accepte pas l'offre, sans pour autant différer les travaux, il reçoit sur demande une avance au moins égale aux trois quarts du montant notifié. Cette avance est forfaitaire, elle n'est pas revalorisée, et elle est versée dans les quinze jours de la demande, sans préjudice d'une décision de justice sur le fond. À défaut de versement dans ce délai, l'assuré peut engager les dépenses dans la limite de l'offre déjà notifiée. L'indemnité ne peut excéder le coût nécessaire à la réparation. Elle est affectée à la remise en état effective de l'immeuble ou de son terrain d'assiette, conformément à l'article L.121-17 du Code des assurances. L'assuré ne cumule pas, pour le même poste, l'indemnité dommages-ouvrage et une somme reçue d'un constructeur ou de son assureur au titre du même dommage.",
  "Subrogation. Après paiement, l'assureur est subrogé dans les droits et actions de l'assuré contre les constructeurs et leurs assureurs, dans les limites des articles L.121-12 et L.242-1 du Code des assurances. L'assuré conserve les recours qui excèdent l'indemnité versée. Il ne fait aucun acte qui nuirait à cette subrogation. L'assureur lui notifie, pour information, la position qu'il prend sur ce recours au vu du rapport complémentaire.",
  "Déclarations. Les réponses du questionnaire sont déterminantes du consentement de l'assureur, au sens des articles L.113-2, L.113-8 et L.113-9 du Code des assurances. La réticence ou la fausse déclaration intentionnelle entraîne la nullité du contrat. Lorsque la mauvaise foi n'est pas établie, l'indemnité est réduite en proportion de la prime payée et de celle qui aurait été due si le risque avait été exactement déclaré. Toute aggravation, notamment un changement de destination, de technique, de coût ou d'intervenant, est déclarée avant l'exécution des travaux concernés. L'article L.113-4 permet alors à l'assureur de proposer une prime nouvelle ou de dénoncer le contrat dans les délais de cet article, qu'il rappelle à l'assuré. Cette faculté ne peut pas éteindre la garantie obligatoire déjà en effet. L'assureur ne peut plus invoquer l'aggravation s'il a accepté de maintenir la garantie, notamment en encaissant la prime ou en payant une indemnité après en avoir été informé.",
  "Déchéances. Une déchéance pour déclaration tardive du sinistre ne peut être opposée lorsque le retard résulte d'un cas fortuit ou d'une force majeure. L'article L.113-11 du Code des assurances frappe de nullité la clause qui prévoirait cette déchéance, la clause générale de déchéance pour violation des lois ou des règlements sauf crime ou délit intentionnel, et la déchéance fondée sur un simple retard à déclarer le sinistre aux autorités ou à produire des pièces. Ce retard laisse à l'assureur le droit de demander une indemnité proportionnée au préjudice qu'il lui a causé. Aucune déchéance ne peut ramener la garantie obligatoire au-dessous de l'annexe II à l'article A.243-1.",
  "Champ de l'obligation. L'article L.243-1-1 du Code des assurances écarte l'obligation pour les ouvrages maritimes, lacustres et fluviaux, les infrastructures routières, portuaires, aéroportuaires, héliportuaires et ferroviaires, les ouvrages de traitement de résidus urbains, de déchets industriels et d'effluents, ainsi que les éléments d'équipement de ces ouvrages. Sauf lorsqu'ils sont l'accessoire d'un ouvrage soumis à l'obligation, les voiries, ouvrages piétonniers, parcs de stationnement, réseaux, canalisations, lignes et câbles, ouvrages de transport, de production, de stockage et de distribution d'énergie, ouvrages de stockage de solides, fluides et liquides, ouvrages de télécommunications et ouvrages sportifs non couverts sont également hors obligation, avec leurs éléments d'équipement. Un ouvrage qui n'est pas visé par cet article reste soumis à l'obligation, même s'il est l'accessoire d'un ouvrage exclu. Les existants antérieurs à l'ouverture du chantier n'y entrent que s'ils sont totalement incorporés dans l'ouvrage neuf et en deviennent techniquement indivisibles. Une opération qui n'atteint ni les fondations, ni l'ossature, ni le clos, ni le couvert peut échapper à l'obligation : elle est qualifiée d'après le questionnaire, avant toute garantie.",
  "Dommages exclus. Les exclusions qui suivent sont rédigées en caractères apparents, conformément à l'article L.112-4 du Code des assurances. La garantie obligatoire ne s'applique pas aux dommages résultant exclusivement du fait intentionnel ou du dol du souscripteur ou de l'assuré, des effets de l'usure normale, du défaut d'entretien ou de l'usage anormal, et de la cause étrangère. Restent également hors garantie les dommages connus du souscripteur avant la date d'effet, les vices apparents à la réception, les travaux non déclarés, les ouvrages inscrits ou classés au titre des monuments historiques, et les dommages dus à la guerre, à l'émeute ou au terrorisme. Ces exclusions ne peuvent pas ramener la garantie obligatoire au-dessous de l'annexe II à l'article A.243-1. Les catastrophes naturelles suivent le régime qui leur est propre et ne sont pas une extension automatique du présent contrat.",
  "Technique courante. Les travaux doivent être exécutés selon les règles de l'art, les normes et les documents techniques applicables. Un procédé, un avis technique d'expérimentation ou une technique non courante est déclaré avant sa mise en œuvre. Sans acceptation écrite, il reste hors garantie. Une portée horizontale entre appuis supérieure à sept mètres, un terrain de pente supérieure à 30 %, ou une étude de sol manquante alors qu'elle est exigée, font obstacle à la garantie.",
  "Constructeurs. L'article 1792-1 du Code civil vise notamment l'architecte, l'entrepreneur, le technicien lié au maître d'ouvrage par un contrat de louage d'ouvrage, le vendeur après achèvement et le fabricant d'un élément pouvant entraîner la responsabilité solidaire. Chaque intervenant justifie, pour son lot, de l'assurance des articles L.241-1 et L.241-2 du Code des assurances, en cours à l'ouverture du chantier. Seuls les intervenants et les lots déclarés sont tenus pour réalisateurs. Un intervenant nouveau est déclaré, avec son attestation, avant d'intervenir. Le maître d'ouvrage déclare s'il exécute lui-même une partie des travaux ou une mission de maîtrise d'œuvre : cette part, qui ne relève pas de l'article 1792-1 pour ce qu'il réalise personnellement, reste hors garantie tant qu'elle n'a pas été acceptée.",
  "Missions intellectuelles et de contrôle. Lorsque le chantier y répond, sont exigés une étude de sol de type G2 AVP, une maîtrise d'œuvre ou un architecte en mission complète, un contrôleur technique L ou LE, et un bureau d'études structure, selon les seuils indiqués à la proposition. Lorsque le Code de la construction et de l'habitation impose un contrôle technique, son absence est une aggravation du risque. Les avis de ces intervenants sont suivis. Les pièces correspondantes sont remises avant l'ouverture du chantier.",
  "Pièces et suspension. Dans le mois de l'achèvement, l'assuré remet la déclaration d'achèvement, le décompte définitif signé et ventilé par corps d'état, les procès-verbaux de réception, la levée des réserves ou la mise en demeure recommandée tendant à cette levée, les factures et les attestations décennales valables à l'ouverture du chantier, ainsi que le rapport final du contrôle technique lorsqu'il est exigé. Jusqu'à cette remise, la garantie est suspendue en cas de sinistre. Les déchéances ne peuvent pas réduire la garantie obligatoire en deçà des clauses types ; elles s'appliquent lorsque l'assuré n'a pas satisfait aux obligations déclaratives et documentaires rappelées aux présentes.",
  "Obligations en cours de chantier. L'assuré déclare tout arrêt de travaux de plus de trente jours. Il remet, dans le mois de l'achèvement, un dossier technique comprenant au moins les plans et descriptifs des travaux réellement exécutés, les réserves non levées du contrôleur technique et le constat des travaux exécutés au titre du parfait achèvement. Il communique à l'assureur les avis du contrôleur technique en même temps qu'au réalisateur concerné, et il ne s'oppose pas à ce que l'assureur interroge ce contrôleur, à ses frais, sous le couvert du maître de l'ouvrage. Il autorise l'accès au chantier jusqu'à la fin du parfait achèvement, puis l'accès aux lieux en cas de sinistre. Les notifications entre les parties prévues pour le sinistre et pour ces obligations sont faites par écrit, contre récépissé ou par lettre recommandée avec avis de réception.",
  "Clos et couvert. Si cette option est souscrite, la garantie est limitée aux lots de terrassement, de voiries et réseaux, de gros œuvre, de charpente, de couverture et de menuiseries extérieures. Cette limite est portée à la connaissance des acquéreurs et figure sur les actes. Elle ne dispense pas le maître d'ouvrage de l'obligation légale d'assurance pour les travaux qui restent soumis à l'article L.242-1 et qui ne sont pas compris dans l'option.",
  "Prime et prise d'effet. La proposition, établie selon l'article L.112-2 du Code des assurances, n'engage ni le candidat ni l'assureur : seule la police constate l'engagement réciproque. La garantie naît à la date d'effet indiquée aux conditions particulières, après questionnaire complet, conditions particulières signées et encaissement de la prime. Le défaut de paiement de la prime initiale empêche la prise d'effet. Pour une garantie facultative expressément souscrite, le régime de l'article L.113-3 du Code des assurances peut suspendre puis résilier cette seule garantie en cas de non-paiement, sans atteindre la garantie obligatoire déjà en effet.",
  "Distribution et conseil. Optimum Courtage agit en qualité de courtier, sans obligation de travailler exclusivement avec un assureur, et par délégation de l'assureur porteur du risque. Toute entreprise d'assurance agréée au sens de l'article L.321-1 du Code des assurances est habilitée à couvrir le risque dommages-ouvrage, même si elle n'assure pas la responsabilité décennale. Le courtier remet une information claire au sens des articles L.521-2 et suivants du même code et exécute son devoir de conseil. La rémunération de courtage et les frais figurent sur la proposition et entrent dans le montant total TTC. L'indemnisation du sinistre incombe à l'assureur, non au courtier. Le contrat est rédigé en français, en caractères apparents, conformément à l'article L.112-3.",
  "Preuve et signature. Le questionnaire, la proposition acceptée avec la mention « Bon pour accord », les conditions particulières et la preuve de l'encaissement forment le contrat avec les conditions générales accessibles sur le site. L'écrit électronique et la signature électronique font foi dans les conditions des articles 1366 et 1367 du Code civil. Le paraphe de chaque page est demandé sur la proposition.",
  "Prescription de l'action contre l'assureur. L'action dérivant du contrat d'assurance se prescrit par deux ans à compter de l'événement qui y donne naissance, selon l'article L.114-1 du Code des assurances. Ce délai court, pour l'assuré, du jour où il a connu le dommage de nature à mettre en jeu la garantie, et au plus tard du jour où ce dommage s'est manifesté. Il est interrompu dans les cas de l'article L.114-2 : par les causes ordinaires du Code civil, notamment la reconnaissance par le débiteur du droit de celui contre lequel il prescrivait (article 2240), la demande en justice (article 2241) et l'acte d'exécution forcée (article 2244), par la désignation d'experts à la suite d'un sinistre, et par l'envoi d'une lettre recommandée avec avis de réception, de l'assuré à l'assureur pour le règlement de l'indemnité ou de l'assureur à l'assuré pour le paiement de la prime. Ce rappel est fait conformément à l'article R.112-1 : sans lui, l'assureur ne pourrait opposer la prescription biennale. Cette prescription ne se confond pas avec la forclusion décennale de l'article 1792-4-1 du Code civil, qui éteint la garantie elle-même dix ans après la réception.",
  "Renonciation. Une personne physique qui souscrit à distance ou hors établissement, pour des besoins qui n'entrent pas dans son activité commerciale ou professionnelle, peut renoncer pendant quatorze jours calendaires dans les conditions de l'article L.112-2-1 du Code des assurances, sans motif ni pénalité. La renonciation est adressée au courtier sur un support durable et indique le numéro de proposition ou de contrat. Si l'intéressé a demandé l'exécution immédiate avant la fin du délai, la prime correspondant à la période déjà courue reste due.",
  "Réclamation puis médiation. Toute réclamation est d'abord adressée par écrit au courtier, à " +
    DEFAULT_PUBLIC_CONTACT_EMAIL +
    ". Elle est accusée réception dans les dix jours et reçoit une réponse au plus tard dans les deux mois. Passé ce délai, ou en cas de désaccord, le souscripteur peut saisir gratuitement La Médiation de l'Assurance, TSA 50110, 75441 Paris Cedex 09, www.mediation-assurance.org, si le litige n'est pas déjà porté devant un tribunal. La saisine du médiateur n'interdit pas une action en justice et n'interrompt la prescription que dans les conditions de la loi.",
  "Personnes politiquement exposées et vigilance. Le souscripteur déclare que ni lui, ni son conjoint, ni ses enfants, ni ses parents ne sont des personnes politiquement exposées au sens de l'article R.561-18 du Code monétaire et financier. Le courtier applique les obligations de vigilance des articles L.561-2 et suivants du même code. Le refus de justifier de l'identité ou de l'origine des fonds bloque l'émission des pièces et peut empêcher la prise d'effet.",
  "Droit applicable. Le contrat est soumis au droit français. Les tribunaux français sont compétents. En cas de divergence, les conditions particulières prévalent sur les conditions générales, et le minimum des clauses types de l'article A.243-1 prévaut sur toute stipulation moins favorable au titre de la seule garantie obligatoire.",
] as const

export const DO_CP_CADRE = [
  "En cas de divergence, les conditions particulières prévalent sur les conditions générales.",
  "Le contrat est composé des présentes conditions particulières, du questionnaire d'étude du risque et des conditions générales remises au souscripteur.",
  "La garantie dommages-ouvrage est attachée à l'ouvrage désigné, pour les travaux décrits aux présentes. Seule l'assurance obligatoire des articles L.242-1 et L.242-2 du Code des assurances est acquise, sauf mention contraire.",
  "L'assurance s'applique aux opérations situées en France métropolitaine, en Corse, en Guadeloupe, en Martinique, en Guyane et à La Réunion, à l'adresse de chantier indiquée.",
  "Franchise : aucune sur la garantie obligatoire dommages-ouvrage.",
  "Habitation : indemnisation à hauteur du coût de réparation des dommages. Hors habitation : à hauteur du coût de réparation, dans la limite du coût total de construction déclaré.",
  "Les garanties sont conditionnées au coût total de construction déclaré, honoraires et existants inclus, et à une souscription antérieure à la réception de l'ouvrage.",
  "La prise d'effet est conditionnée à l'encaissement de la prime et au retour des conditions particulières signées.",
  "Si le coût définitif dépasse de plus de 10 % le coût prévisionnel déclaré, la prime est ajustée au même taux et un avenant est établi.",
  "Lorsque la prime a été calculée hors taxes, les indemnités sont réglées hors taxes jusqu'à l'avenant qui intègre la TVA.",
  "En cas de vente de l'ouvrage, l'assuré en informe l'assureur et l'acquéreur. Si la garantie est limitée au clos et couvert, cette limitation est indiquée aux acquéreurs et figure sur les actes.",
  "Seuls les intervenants déclarés au questionnaire, avec le lot qu'ils réalisent, sont des réalisateurs. Tout intervenant nouveau est déclaré avant son intervention.",
  "Dans le mois qui suit la fin des travaux, l'assuré remet la déclaration d'achèvement, le décompte définitif signé par le maître d'ouvrage, les procès-verbaux de réception signés, la levée des réserves, les factures des intervenants et les attestations de responsabilité civile décennale valables à l'ouverture du chantier. À défaut de remise, la garantie est suspendue en cas de sinistre.",
  "Le maître d'ouvrage déclare que chaque intervenant justifie de l'assurance prévue aux articles L.241-1 et L.241-2 du Code des assurances, et qu'il n'exécute pas lui-même une mission de maîtrise d'œuvre ni les travaux, sauf mention acceptée.",
  "Les déclarations du questionnaire sont déterminantes du consentement de l'assureur. Toute omission ou inexactitude relève des articles L.113-8 et L.113-9 du Code des assurances.",
  "Le souscripteur déclare ne pas être une personne politiquement exposée au sens de l'article R.561-18 du Code monétaire et financier, ni l'être son conjoint, ses enfants ou ses parents.",
  "Sont notamment exclus les sinistres connus du souscripteur avant la date d'effet et les travaux sur un ouvrage inscrit ou classé monument historique.",
  "Durée : garantie unique de dix ans à compter de la réception pour la garantie obligatoire. Cette garantie obligatoire n'est pas résiliable.",
  "Tout litige relatif au contrat relève du droit français et des tribunaux français.",
  "Protection juridique : défense et recours selon les conditions contractuelles applicables. L'indemnisation du sinistre incombe à l'assureur. Le courtier distribue le contrat et transmet la déclaration.",
  ...DO_MENTIONS_JURIDIQUES,
] as const

export const DO_GARANTIE_OBLIGATOIRE_LIGNE =
  "Garantie obligatoire dommages-ouvrage : souscrite, sans franchise. Habitation : à hauteur du coût de réparation des dommages. Hors habitation : à hauteur du coût de réparation, dans la limite du coût total de construction déclaré."

/** Garanties facultatives : absentes tant qu'elles ne sont pas cochées sur la proposition. */
export const DO_GARANTIES_NON_SOUSCRITES = [
  "Garanties complémentaires (bon fonctionnement des éléments d'équipement et dommages immatériels) : non souscrites, sauf mention expresse. Lorsqu'elles sont souscrites, leur plafond est de 15 % du coût total de la construction, épuisable.",
  "Garantie des dommages causés aux existants : non souscrite, sauf mention expresse. Lorsqu'elle est souscrite, elle est limitée au montant déclaré des existants, dans la limite de 250 000 EUR, épuisable.",
  "Constructeur non réalisateur, tous risques chantier et responsabilité civile du maître d'ouvrage : non souscrits, sauf mention expresse sur la proposition.",
] as const

export const DO_MISSIONS_OBLIGATOIRES = [
  "Étude de sol G2 AVP : construction neuve de plus de 300 000 EUR ; extension dont la surface créée dépasse de plus de 50 % la surface existante ; pente du terrain comprise entre 15 % et 30 % ; présence ou construction d'une piscine. Une pente supérieure à 30 % n'est pas garantie.",
  "Maître d'œuvre ou architecte en mission complète : à partir de 300 000 EUR de travaux.",
  "Contrôleur technique L, ou LE lorsqu'il existe des ouvrages existants : à partir de 500 000 EUR de travaux.",
  "Bureau d'études structure : à partir de R+3 en construction neuve, et en réhabilitation ou rénovation lorsqu'il y a atteinte à la structure porteuse.",
] as const

export const DO_PIECES_AVANT_CHANTIER = [
  "Proposition datée, paraphée et signée avec la mention « Bon pour accord ».",
  "Permis de construire ou déclaration préalable, plans, devis descriptif et planning des travaux.",
  "Extrait Kbis du maître d'ouvrage lorsqu'il s'agit d'une société.",
  "Étude de sol, convention et attestation décennale du maître d'œuvre, rapport et convention de contrôle technique, lorsque ces missions sont exigées.",
  "Attestations de responsabilité civile décennale, valables à l'ouverture du chantier, de tous les intervenants liés par un contrat de louage d'ouvrage.",
] as const

export const DO_PIECES_APRES_RECEPTION = [
  "Déclaration d'achèvement des travaux.",
  "Décompte définitif signé par le maître d'ouvrage, ventilé par corps d'état, honoraires inclus.",
  "Procès-verbaux de réception signés par le maître d'ouvrage et par l'entreprise, ainsi que la levée des réserves.",
  "Factures des intervenants et attestations de responsabilité civile décennale valables à l'ouverture du chantier.",
  "Rapport final du contrôle technique lorsque cette mission est exigée.",
] as const

export function doPropositionDetailLines(input?: {
  activities?: readonly string[]
  mode?: "proposition" | "contrat"
}): string[] {
  const mode = input?.mode ?? "proposition"
  const activities = (input?.activities ?? []).map((line) => line.trim()).filter(Boolean)
  const intro =
    mode === "contrat"
      ? "Le présent contrat répond à l'obligation d'assurance des articles L.242-1 et L.242-2 du Code des assurances pour l'ouvrage désigné. Seule l'assurance obligatoire est acquise, sauf mention contraire. La prise d'effet reste subordonnée à l'encaissement de la prime et à la signature des conditions particulières."
      : "Cette proposition répond à l'obligation d'assurance des articles L.242-1 et L.242-2 du Code des assurances pour l'ouvrage désigné. Seule l'assurance obligatoire est proposée, sauf mention contraire. Elle ne vaut pas garantie : la garantie suppose le questionnaire d'étude complet, le retour des conditions particulières signées et l'encaissement de la prime."

  return [
    intro,
    `Le coût total de la construction ne dépasse pas ${DO_COUT_MAX_PROPOSITION_LABEL}. La souscription intervient avant la réception de l'ouvrage.`,
    ...activities,
    DO_GARANTIE_OBLIGATOIRE_LIGNE,
    ...DO_GARANTIES_NON_SOUSCRITES,
    ...DO_MISSIONS_OBLIGATOIRES.map((mission) => `Mission exigée lorsque le chantier y répond : ${mission}`),
    "Lors de l'arrêté définitif des comptes, la prime est ajustée au même taux si le coût définitif dépasse de plus de 10 % le coût prévisionnel déclaré.",
    "Sont notamment exclus les sinistres connus avant la date d'effet et les travaux sur un ouvrage inscrit ou classé monument historique.",
    `Pièces à remettre avant l'ouverture du chantier : ${DO_PIECES_AVANT_CHANTIER.join(" ")}`,
    `Pièces de fin de chantier, dans le mois suivant l'achèvement : ${DO_PIECES_APRES_RECEPTION.join(" ")}`,
    mode === "contrat"
      ? "Les parties signent les conditions particulières. Le contrat et l'attestation émis font foi."
      : "Pour accepter l'offre, retournez la proposition datée et signée, chaque page paraphée, avec la mention « Bon pour accord ».",
  ]
}

export function decennaleGarantieClauseLines(data: {
  franchise?: unknown
  plafond?: unknown
  chiffreAffaires?: unknown
}): string[] {
  return decennaleGarantieRows(data).map(
    (row) => `${row.nom} — plafond ${row.plafond}, franchise ${row.franchise}. ${row.description}`
  )
}

export function doGarantieClauseLines(): string[] {
  return [DO_GARANTIES_LEGALES.I1, DO_GARANTIES_LEGALES.I2, DO_GARANTIES_LEGALES.I3].map(
    (row) => `${row.libelle} — ${row.duree}. ${row.description}`
  )
}

/** Cadre opérationnel et régime juridique de la responsabilité décennale, sans le tableau des montants. */
export function decennaleCadreCompletLines(): string[] {
  return [...DECENNALE_CP_CADRE, ...DECENNALE_REGIME_EXPERT]
}

export function decennaleConditionsParticulieresLines(data: {
  franchise?: unknown
  plafond?: unknown
  chiffreAffaires?: unknown
} = {}): string[] {
  return [...decennaleCadreCompletLines(), ...decennaleGarantieClauseLines(data)]
}

/** Cadre opérationnel et régime juridique développé, sans répétition du tableau des garanties. */
export function doCadreCompletLines(): string[] {
  return [...DO_CP_CADRE, ...DO_REGIME_EXPERT]
}

export function doConditionsParticulieresLines(): string[] {
  return [...doCadreCompletLines(), ...doGarantieClauseLines()]
}
