export const DECENNALE_EXCLUSIONS_LEGALES_TITLE =
  "EXCLUSIONS LA RESPONSABILITE CIVILE DECENNALE"

export const DECENNALE_EXCLUSIONS_LEGALES_PARAGRAPHS = [
  "CONFORMEMENT A L'ANNEXE II DE L'ARTICLE A. 243-1 DU CODE DES ASSURANCES, LA GARANTIE DECENNALE NE S'APPLIQUE PAS AUX DOMMAGES RESULTANT EXCLUSIVEMENT : DU FAIT INTENTIONNEL OU DU DOL DU SOUSCRIPTEUR OU DE L'ASSURE ; DES EFFETS DE L'USURE NORMALE, DU DEFAUT D'ENTRETIEN OU DE L'USAGE ANORMAL ; DE LA CAUSE ETRANGERE.",
  "LA RESPONSABILITE CIVILE PROFESSIONNELLE : LA GARANTIE RESPONSABILITE CIVILE PROFESSIONNELLE NE S'APPLIQUE PAS DANS LES TROIS CAS VISES CI-DESSUS EN SUS DES CAS PREVUES AUX ARTICLES 3.3.4 DES CONDITIONS GENERALES.",
] as const

export const DECENNALE_DECHEANCE_GARANTIE_TITLE = "DECHEANCE DE GARANTIE"

export const DECENNALE_DECHEANCE_GARANTIE_PARAGRAPHS = [
  "SANS PREJUDICE DES DECHEANCES OPPOSABLES EN DEHORS DE LA GARANTIE RESPONSABILITE CIVILE DECENNALE OBLIGATOIRE ET CONFORMEMENT A L'ANNEXE I DE L'ARTICLE A.243-1 DU CODE DES ASSURANCES, L'ASSURE EST DECHU DE TOUT DROIT A GARANTIE EN CAS D'INOBSERVATION INEXCUSABLE DES REGLES DE L'ART, TELLES QU'ELLES SONT DEFINIES PAR LES REGLEMENTATIONS EN VIGUEUR, LES NORMES FRANCAISES HOMOLOGUEES OU LES NORMES PUBLIEES PAR LES ORGANISMES DE NORMALISATION D'UN AUTRE ETAT MEMBRE DE L'UNION EUROPEENNE OU D'UN AUTRE ETAT PARTIE A L'ACCORD SUR L'ESPACE ECONOMIQUE EUROPEEN OFFRANT UN DEGRE DE SECURITE ET DE PERENNITE EQUIVALANT A CELUI DES NORMES FRANCAISES.",
  "POUR L'APPLICATION DE CETTE DECHEANCE, IL FAUT ENTENDRE PAR ASSURE, SOIT LE SOUSCRIPTEUR PERSONNE PHYSIQUE, SOIT LE CHEF D'ENTREPRISE OU LE REPRESENTANT STATUTAIRE DE L'ENTREPRISE S'IL S'AGIT D'UNE ENTREPRISE INSCRITE AU REPERTOIRE DES METIERS, SOIT LES REPRESENTANTS LEGAUX OU DUMENT MANDATES DE L'ASSURE LORSQUE CELUI-CI EST UNE PERSONNE MORALE.",
  "CETTE DECHEANCE N'EST PAS OPPOSABLE AUX BENEFICIAIRES DES INDEMNITES DUES AU TITRE DE LA GARANTIE RESPONSABILITE CIVILE DECENNALE OBLIGATOIRE.",
] as const

/**
 * Exports de compatibilité utilisés dans les templates/pdfs existants.
 */
export const DECENNALE_LEGAL_CLAUSES = {
  EXCLUSIONS_RC_DECENNALE: [
    DECENNALE_EXCLUSIONS_LEGALES_TITLE,
    ...DECENNALE_EXCLUSIONS_LEGALES_PARAGRAPHS,
  ].join(" "),
  DECHEANCE_GARANTIE: [
    DECENNALE_DECHEANCE_GARANTIE_TITLE,
    ...DECENNALE_DECHEANCE_GARANTIE_PARAGRAPHS,
  ].join(" "),
} as const

export const DECENNALE_EXCLUSIONS_AND_DECHEANCE_CLAUSE_TEXT = [
  DECENNALE_LEGAL_CLAUSES.EXCLUSIONS_RC_DECENNALE,
  DECENNALE_LEGAL_CLAUSES.DECHEANCE_GARANTIE,
].join("\n\n")

export const DECENNALE_EXCLUSIONS_AND_DECHEANCE_CLAUSES =
  DECENNALE_EXCLUSIONS_AND_DECHEANCE_CLAUSE_TEXT

export const DECENNALE_CUSTOM_LEGAL_CLAUSES = [
  DECENNALE_LEGAL_CLAUSES.EXCLUSIONS_RC_DECENNALE,
  DECENNALE_LEGAL_CLAUSES.DECHEANCE_GARANTIE,
] as const

export const DECENNALE_CLAUSE_BLOCS = {
  exclusionsResponsabiliteCivileDecennaleTitre: DECENNALE_EXCLUSIONS_LEGALES_TITLE,
  exclusionsResponsabiliteCivileDecennaleParagraphe: DECENNALE_EXCLUSIONS_LEGALES_PARAGRAPHS.join(" "),
  exclusionsResponsabiliteCivileDecennaleContenu: DECENNALE_EXCLUSIONS_LEGALES_PARAGRAPHS.join(" "),
  decheanceGarantieTitre: DECENNALE_DECHEANCE_GARANTIE_TITLE,
  decheanceGarantieParagraphe: DECENNALE_DECHEANCE_GARANTIE_PARAGRAPHS.join(" "),
  decheanceGarantieContenu: DECENNALE_DECHEANCE_GARANTIE_PARAGRAPHS.join(" "),
} as const
