export type InsuranceDocumentProduct = "decennale" | "do" | "rc_fabriquant" | "assurance_titre"

export function parseJsonObject(raw: string | null | undefined): Record<string, unknown> {
  if (!raw?.trim()) return {}
  try {
    const parsed = JSON.parse(raw)
    if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
      return parsed as Record<string, unknown>
    }
  } catch {
    // Invalid legacy document data should be treated as unknown.
  }
  return {}
}

function normalizedString(value: unknown): string {
  return typeof value === "string" ? value.trim().toLowerCase() : ""
}

function readExplicitProduct(data: Record<string, unknown>): InsuranceDocumentProduct | null {
  const raw = normalizedString(data.insuranceProduct) || normalizedString(data.productType)
  if (raw === "do" || raw === "dommage-ouvrage" || raw === "dommage_ouvrage") return "do"
  if (raw === "rc_fabriquant" || raw === "rc-fabriquant") return "rc_fabriquant"
  if (raw === "assurance_titre" || raw === "assurance-titre") return "assurance_titre"
  if (raw === "decennale" || raw === "décennale") return "decennale"
  return null
}

export function inferDocumentProduct(data: Record<string, unknown>): InsuranceDocumentProduct {
  const explicit = readExplicitProduct(data)
  if (explicit) return explicit

  // Legacy DO platform payloads can be recognized by project fields even when productType was not stored.
  if (normalizedString(data.doProjectName) || normalizedString(data.projectName) || normalizedString(data.projectAddress)) {
    return "do"
  }

  // Legacy signed documents without product marker were generated by the décennale flow.
  return "decennale"
}

export function isDecennaleContractData(raw: string | null | undefined): boolean {
  const data = parseJsonObject(raw)
  if (data.customUploadedDevisFlow === true) return false
  return inferDocumentProduct(data) === "decennale"
}

export function isDecennalePendingSignatureData(raw: string | null | undefined): boolean {
  const data = parseJsonObject(raw)
  if (data.customUploadedDevisFlow === true) return false
  return inferDocumentProduct(data) === "decennale"
}
